name: RecoveryLog
options:
  bundleIdPrefix: com.shimondeitel.recoverylog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  RecoveryLog:
    type: application
    platform: iOS
    sources:
      - path: RecoveryLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.recoverylog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: RecoveryLog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  RecoveryLogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RecoveryLogTests
      - path: RecoveryLog.storekit
    dependencies:
      - target: RecoveryLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.recoverylog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  RecoveryLogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: RecoveryLogUITests
    dependencies:
      - target: RecoveryLog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.recoverylog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  RecoveryLog:
    build:
      targets:
        RecoveryLog: all
        RecoveryLogTests: [test]
        RecoveryLogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: RecoveryLog.storekit
    test:
      config: Debug
      storeKitConfiguration: RecoveryLog.storekit
      targets:
        - RecoveryLogTests
        - RecoveryLogUITests
    archive:
      config: Release
